#include "blog.h"

// Generated by cppfront v0.8.2 build AA17:1543
#ifndef SCOPE_H_CPP2
#define SCOPE_H_CPP2

#define CPP2_IMPORT_STD Yes
#define CPP2_NO_EXCEPTIONS Yes

#include "cpp2util.h"

template <typename TCallback>
  requires(std::is_invocable_v<TCallback>)
class OnScopeExit;

class ScopedTimer;

template <typename TCallback>
  requires(std::is_invocable_v<TCallback>)
class OnScopeExit {
public:
  OnScopeExit(TCallback const &func);

public:
  auto operator=(TCallback const &func) -> OnScopeExit &;

public:
  ~OnScopeExit() noexcept;

private:
  TCallback m_callOnExit{};

public:
  OnScopeExit(OnScopeExit const &) =
      delete; /* No 'that' constructor, suppress copy */
public:
  auto operator=(OnScopeExit const &) -> void = delete;
};

// simple timer for measuring execution speed of blocks of code; logs "X took Y"
// on scope exit
class ScopedTimer {
private:
  using TTimeClock = std::chrono::high_resolution_clock;

private:
  using TTimePoint = std::chrono::time_point<TTimeClock>;

public:
  ScopedTimer(cpp2::impl::in<std::string_view> context);

public:
  auto operator=(cpp2::impl::in<std::string_view> context) -> ScopedTimer &;

public:
  ~ScopedTimer() noexcept;

private:
  std::string m_context{};

private:
  TTimePoint m_timeAtStart{TTimeClock::now()};

public:
  ScopedTimer(ScopedTimer const &) =
      delete; /* No 'that' constructor, suppress copy */
public:
  auto operator=(ScopedTimer const &) -> void = delete;
};

template <typename TCallback>
  requires(std::is_invocable_v<TCallback>)
OnScopeExit<TCallback>::OnScopeExit(TCallback const &func) : m_callOnExit{func}
{
}

template <typename TCallback>
  requires(std::is_invocable_v<TCallback>)
auto OnScopeExit<TCallback>::operator=(TCallback const &func) -> OnScopeExit &
{
  m_callOnExit = func;
  return *this;
}

template <typename TCallback>
  requires(std::is_invocable_v<TCallback>)
OnScopeExit<TCallback>::~OnScopeExit() noexcept
{
  cpp2::move(*this).m_callOnExit();
}

ScopedTimer::ScopedTimer(cpp2::impl::in<std::string_view> context)
    : m_context{context}
{
}

auto ScopedTimer::operator=(cpp2::impl::in<std::string_view> context)
    -> ScopedTimer &
{
  m_context = context;
  m_timeAtStart = TTimeClock::now();
  return *this;
}

ScopedTimer::~ScopedTimer() noexcept
{
  auto timeAtEnd{TTimeClock::now()};

  // is there a nicer way to get fractional seconds out of chrono?..
  auto duration{std::chrono::duration_cast<std::chrono::milliseconds>(
      cpp2::move(timeAtEnd) - m_timeAtStart)};
  auto durationTicks{
      cpp2::unchecked_narrow<double>(CPP2_UFCS(count)(cpp2::move(duration)))};

  blog::app(
      "{} took {}s", cpp2::move(*this).m_context,
      cpp2::move(durationTicks) /
          CPP2_ASSERT_NOT_ZERO(CPP2_TYPEOF(cpp2::move(durationTicks)), 1000.0));
}
#endif
